<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>DInventory.Web</RootNamespace>
    <UserSecretsId>dinventory-web-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DInventory.Application\DInventory.Application.csproj" />
    <ProjectReference Include="..\DInventory.Infrastructure\DInventory.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="App_Data\Database.sql">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\fonts\" />
  </ItemGroup>

</Project>
